/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;




/**
 *
 * @author Rodrigo
 */
public class JanelaCalculadora extends javax.swing.JPanel {

    /**
     * Creates new form JanelaCalculadora
     */
    public JanelaCalculadora() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoSomar = new javax.swing.JButton();
        BotaoSub = new javax.swing.JButton();
        BotaoMult = new javax.swing.JButton();
        BotaoDivi = new javax.swing.JButton();
        Campon1 = new javax.swing.JTextField();
        Campon2 = new javax.swing.JTextField();
        CampoResultado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 255));
        setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        BotaoSomar.setBackground(new java.awt.Color(0, 0, 204));
        BotaoSomar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoSomar.setText("Somar");
        BotaoSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSomarActionPerformed(evt);
            }
        });

        BotaoSub.setBackground(new java.awt.Color(0, 0, 204));
        BotaoSub.setForeground(new java.awt.Color(255, 255, 255));
        BotaoSub.setText("Subtrair");

        BotaoMult.setBackground(new java.awt.Color(0, 0, 204));
        BotaoMult.setForeground(new java.awt.Color(255, 255, 255));
        BotaoMult.setText("Multiplicação");

        BotaoDivi.setBackground(new java.awt.Color(0, 0, 204));
        BotaoDivi.setForeground(new java.awt.Color(255, 255, 255));
        BotaoDivi.setText("Divisão");

        Campon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campon1ActionPerformed(evt);
            }
        });

        CampoResultado.setBackground(new java.awt.Color(102, 255, 255));
        CampoResultado.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CampoResultado.setForeground(new java.awt.Color(51, 51, 51));
        CampoResultado.setBorder(null);
        CampoResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoResultadoActionPerformed(evt);
            }
        });

        jLabel1.setText("Digite um Numero:");

        jLabel2.setText("Digite outro Numero:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Calculadora 3.0");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Resultado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Campon2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Campon1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotaoSomar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotaoSub)
                                .addGap(18, 18, 18)
                                .addComponent(BotaoMult))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(BotaoDivi)))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Campon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Campon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoDivi)
                    .addComponent(BotaoMult)
                    .addComponent(BotaoSub)
                    .addComponent(BotaoSomar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CampoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Campon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campon1ActionPerformed

    private void BotaoSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSomarActionPerformed

    }//GEN-LAST:event_BotaoSomarActionPerformed

    private void CampoResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoResultadoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoDivi;
    private javax.swing.JButton BotaoMult;
    private javax.swing.JButton BotaoSomar;
    private javax.swing.JButton BotaoSub;
    private javax.swing.JTextField CampoResultado;
    private javax.swing.JTextField Campon1;
    private javax.swing.JTextField Campon2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getCampoResultado() {
        return CampoResultado;
    }

    public void setCampoResultado(javax.swing.JTextField CampoResultado) {
        this.CampoResultado = CampoResultado;
    }

    public javax.swing.JTextField getCampon1() {
        return Campon1;
    }

    public void setCampon1(javax.swing.JTextField Campon1) {
        this.Campon1 = Campon1;
    }

    public javax.swing.JTextField getCampon2() {
        return Campon2;
    }

    public void setCampon2(javax.swing.JTextField Campon2) {
        this.Campon2 = Campon2;
    }

    public javax.swing.JButton getBotaoDivi() {
        return BotaoDivi;
    }

    public void setBotaoDivi(javax.swing.JButton BotaoDivi) {
        this.BotaoDivi = BotaoDivi;
    }

    public javax.swing.JButton getBotaoMult() {
        return BotaoMult;
    }

    public void setBotaoMult(javax.swing.JButton BotaoMult) {
        this.BotaoMult = BotaoMult;
    }

    public javax.swing.JButton getBotaoSub() {
        return BotaoSub;
    }

    public void setBotaoSub(javax.swing.JButton BotaoSub) {
        this.BotaoSub = BotaoSub;
    }

    public javax.swing.JButton getBotaoSomar() {
        return BotaoSomar;
    }

    public void setBotaoSomar(javax.swing.JButton BotaoSomar) {
        this.BotaoSomar = BotaoSomar;
    }

}
